import './loading.css'

function LoadingComponent(){
    return(
        <div className="loadingWrapper">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            <img alt="loading icon" id="loading" src="https://img.icons8.com/doodle/344/pizza--v1.png"></img>
        </div>
    )
}

export default LoadingComponent